# Use node image as base
FROM node:alpine

# Set working directory in the container
WORKDIR /usr/src

# Copy only necessary Angular-related files
COPY ./package.json ./package.json
COPY ./package-lock.json ./package-lock.json
COPY ./angular.json ./angular.json
COPY ./tsconfig.json ./tsconfig.json
COPY ./tsconfig.spec.json ./tsconfig.spec.json
COPY ./tsconfig.app.json ./tsconfig.app.json
COPY ./src/main/webapp ./src/main/webapp
COPY ./proxy.conf.js ./proxy.conf.js

# Install Angular CLI
RUN npm install -g @angular/cli

# Install dependencies
RUN npm install --legacy-peer-deps

ENV NODE_OPTIONS="--openssl-legacy-provider"

# Expose the port
EXPOSE 4300

# Command to run the Angular application
ENTRYPOINT ["ng", "serve", "--host", "0.0.0.0"]
