# Stage 1: Build Angular app
FROM node:alpine AS builder

# Set working directory in the container
WORKDIR /usr/src/app

# Copy only necessary Angular-related files
COPY ./dist ./dist

# Stage 2: Serve Angular app with NGINX
FROM nginx:alpine

# Copy built Angular app from the builder stage
COPY --from=builder /usr/src/app/dist /usr/share/nginx/html
EXPOSE 4200
