# Stage 2: Serve Angular app with NGINX
FROM nginx:alpine
# Copy built Angular app from the builder stage
COPY ./dist /usr/share/nginx/html
COPY ./nginx.conf  /etc/nginx/conf.d/default.conf
EXPOSE 4300
